<?php
/**
 * Admission Number Service
 *
 * Single source of truth for the admission-number format. The configured
 * format lives in school_settings.admission_no_format (default
 * `KA-{year}-{seq:04}`) and supports three tokens:
 *
 *   {year}    -> 4-digit year
 *   {seq}     -> per-year sequence, unpadded
 *   {seq:NN}  -> per-year sequence, zero-padded to NN digits
 *
 * Sequence numbers are generated by the DB function fn_generate_admission_no,
 * which increments the per-year counter in number_sequences atomically so
 * concurrent enrollments never collide. This service adds the PHP-side
 * validation/format helpers used by StudentsAPI::create().
 *
 * @package App\API\Services
 * @since 2026-08-15
 */

namespace App\API\Services;

use PDO;

class AdmissionNumberService
{
    public const DEFAULT_FORMAT = 'KA-{year}-{seq:04}';

    /** @var PDO */
    private $db;

    public function __construct(PDO $db)
    {
        $this->db = $db;
    }

    /**
     * Read the configured admission-number format, falling back to the default.
     */
    public function getFormat(): string
    {
        $stmt = $this->db->prepare("SELECT setting_value FROM school_settings WHERE setting_key = 'admission_no_format' LIMIT 1");
        $stmt->execute();
        $format = $stmt->fetchColumn();

        return ($format === false || $format === null || $format === '') ? self::DEFAULT_FORMAT : (string) $format;
    }

    /**
     * Generate the next admission number for the given year using the DB
     * function (collision-safe, per-year sequence).
     */
    public function generate(int $year): string
    {
        $stmt = $this->db->prepare("SELECT fn_generate_admission_no(:year)");
        $stmt->execute(['year' => $year]);
        $number = $stmt->fetchColumn();

        return (string) $number;
    }

    /**
     * Build a PCRE pattern from a format template so an existing admission
     * number can be validated against the configured format.
     */
    public function buildPattern(string $format): string
    {
        $pattern = '';

        $i = 0;
        $len = strlen($format);
        while ($i < $len) {
            if (substr($format, $i, 6) === '{year}') {
                $pattern .= '\d{4}';
                $i += 6;
                continue;
            }
            if (substr($format, $i, 5) === '{seq}') {
                $pattern .= '\d+';
                $i += 5;
                continue;
            }
            if (substr($format, $i, 5) === '{seq:') {
                $end = strpos($format, '}', $i);
                $width = $end !== false ? substr($format, $i + 5, $end - ($i + 5)) : '';
                if (ctype_digit($width) && (int) $width > 0) {
                    $pattern .= '\d{' . (int) $width . '}';
                    $i = $end + 1;
                } else {
                    $pattern .= '\d+';
                    $i += 5;
                }
                continue;
            }
            $pattern .= preg_quote($format[$i], '/');
            $i++;
        }

        return '/^' . $pattern . '$/';
    }

    /**
     * Check whether an admission number matches the configured format.
     */
    public function isValid(string $admissionNo, ?string $format = null): bool
    {
        $format = $format ?? $this->getFormat();
        return preg_match($this->buildPattern($format), $admissionNo) === 1;
    }
}
