<?php
/**
 * Staff Number Service
 *
 * Single source of truth for the staff-number format. The configured
 * format lives in school_settings.staff_no_format (default
 * `KPST#{seq}`) and supports two tokens:
 *
 *   {seq}     -> global sequence, unpadded
 *   {seq:NN}  -> global sequence, zero-padded to NN digits
 *
 * Sequence numbers are generated by the DB function fn_generate_staff_no,
 * which increments the global counter in number_sequences atomically so
 * concurrent staff creations never collide. This service adds the PHP-side
 * generation and validation helpers.
 *
 * @package App\API\Services
 * @since 2026-08-20
 */

namespace App\API\Services;

use PDO;

class StaffNumberService
{
    public const DEFAULT_FORMAT = 'KPST#{seq}';

    /** @var PDO */
    private $db;

    public function __construct(PDO $db)
    {
        $this->db = $db;
    }

    /**
     * Read the configured staff-number format, falling back to the default.
     */
    public function getFormat(): string
    {
        $stmt = $this->db->prepare(
            "SELECT setting_value FROM school_settings WHERE setting_key = 'staff_no_format' LIMIT 1"
        );
        $stmt->execute();
        $format = $stmt->fetchColumn();

        return ($format === false || $format === null || $format === '')
            ? self::DEFAULT_FORMAT
            : (string) $format;
    }

    /**
     * Generate the next staff number using the DB function (collision-safe,
     * atomic global sequence).
     */
    public function generate(): string
    {
        $stmt = $this->db->query("SELECT fn_generate_staff_no()");
        $number = $stmt->fetchColumn();

        return (string) $number;
    }

    /**
     * Build a PCRE pattern from a format template so an existing staff
     * number can be validated against the configured format.
     */
    public function buildPattern(string $format): string
    {
        $pattern = '';

        $i = 0;
        $len = strlen($format);
        while ($i < $len) {
            if (substr($format, $i, 5) === '{seq}') {
                $pattern .= '\d+';
                $i += 5;
                continue;
            }
            if (substr($format, $i, 5) === '{seq:') {
                $end = strpos($format, '}', $i);
                $width = $end !== false ? substr($format, $i + 5, $end - ($i + 5)) : '';
                if (ctype_digit($width) && (int) $width > 0) {
                    $pattern .= '\d{' . (int) $width . '}';
                    $i = $end + 1;
                } else {
                    $pattern .= '\d+';
                    $i += 5;
                }
                continue;
            }
            $pattern .= preg_quote($format[$i], '/');
            $i++;
        }

        return '/^' . $pattern . '$/';
    }

    /**
     * Check whether a staff number matches the configured format.
     */
    public function isValid(string $staffNo, ?string $format = null): bool
    {
        $format = $format ?? $this->getFormat();
        return preg_match($this->buildPattern($format), $staffNo) === 1;
    }
}
