CREATE TABLE IF NOT EXISTS parent_meetings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    parent_id INT unsigned DEFAULT NULL,
    student_id INT unsigned DEFAULT NULL,
    created_by INT unsigned NOT NULL,
    meeting_date DATE NOT NULL,
    start_time TIME DEFAULT NULL,
    venue VARCHAR(255) DEFAULT NULL,
    purpose TEXT DEFAULT NULL,
    description TEXT DEFAULT NULL,
    minutes TEXT DEFAULT NULL,
    class_id INT unsigned DEFAULT NULL,
    status ENUM('scheduled','confirmed','cancelled','postponed','completed','held') DEFAULT 'scheduled',
    type ENUM('individual','class','general','pta') DEFAULT 'individual',
    attendance_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE SET NULL,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
