-- 009_fix_academic_transition_data.sql
--
-- Repairs data-quality issues found in the academic module that block the
-- automated year-to-year / term-to-term transition business logic:
--
--   1. academic_class_progression was seeded with a scrambled chain
--      (e.g. Playgroup->Grade 7, PP1->Grade 5, Grade 2->Grade 9) and two rows
--      referenced a non-existent classes.id=13. Rebuilt with the canonical
--      grade ladder Playgroup -> PP1 -> PP2 -> Grade 1 -> ... -> Grade 9.
--   2. academic_year_classes row id=12 referenced classes.id=13 (orphan) and
--      academic_year_class_streams id=17 dangled off it. Removed both.
--   3. PP2 (classes.id=3) had no academic_year_classes / streams for the
--      current year (2026). Added ayc + streams A/B (2 streams rule for ECD).
--   4. academic_year_calendar held 49 orphaned weeks whose
--      academic_year_term_id (7,8,9) matched no academic_year_terms (1,2,3).
--      Purged; the calendar is regenerated by sp_generate_year_calendar (010).
--   5. Set placeholder half-term breaks on the 2026 terms so the generated
--      calendar marks holidays. Replace these with government-issued dates.

-- ---------------------------------------------------------------------------
-- 1. Rebuild academic_class_progression (the "move one step ahead" backbone)
-- ---------------------------------------------------------------------------
DELETE FROM academic_class_progression;

INSERT INTO academic_class_progression (id, source_class_id, target_class_id, progression_type, active) VALUES
    (1, 1, 2,  'standard', 1),  -- Playgroup -> PP1
    (2, 2, 3,  'standard', 1),  -- PP1 -> PP2
    (3, 3, 4,  'standard', 1),  -- PP2 -> Grade 1
    (4, 4, 5,  'standard', 1),  -- Grade 1 -> Grade 2
    (5, 5, 6,  'standard', 1),  -- Grade 2 -> Grade 3
    (6, 6, 7,  'standard', 1),  -- Grade 3 -> Grade 4
    (7, 7, 8,  'standard', 1),  -- Grade 4 -> Grade 5
    (8, 8, 9,  'standard', 1),  -- Grade 5 -> Grade 6
    (9, 9, 10, 'standard', 1),  -- Grade 6 -> Grade 7
    (10, 10, 11, 'standard', 1), -- Grade 7 -> Grade 8
    (11, 11, 12, 'standard', 1); -- Grade 8 -> Grade 9 (Grade 9 graduates: no row)

-- ---------------------------------------------------------------------------
-- 2. Remove orphaned structure (class 13 does not exist)
-- ---------------------------------------------------------------------------
-- 2a. Drop the broken legacy AFTER INSERT trigger: it references the removed
--     academic_year_class_streams.capacity column, so every academic_year_classes
--     insert now fails. Stream creation is owned by the transition workflow's
--     createStreamLink() (reuse-or-create global A/B/C streams).
DROP TRIGGER IF EXISTS trg_auto_create_default_stream;

DELETE FROM academic_year_class_streams WHERE id = 17;
DELETE FROM academic_year_classes WHERE id = 12;

-- ---------------------------------------------------------------------------
-- 3. Add missing PP2 (classes.id=3) to the current year (academic_years.id=1)
-- ---------------------------------------------------------------------------
INSERT INTO academic_year_classes (id, academic_year_id, class_id, status) VALUES (13, 1, 3, 'active');

INSERT INTO academic_year_class_streams (id, academic_year_class_id, stream_id, status) VALUES
    (18, 13, 1, 'active'), -- PP2 A
    (19, 13, 2, 'active'); -- PP2 B

-- ---------------------------------------------------------------------------
-- 4. Purge orphaned academic calendar weeks/days (no matching academic_year_term)
-- ---------------------------------------------------------------------------
DELETE days
FROM academic_year_calendar_days days
JOIN academic_year_calendar c ON c.id = days.academic_year_calendar_id
WHERE c.academic_year_term_id NOT IN (SELECT id FROM academic_year_terms);

DELETE FROM academic_year_calendar
WHERE academic_year_term_id NOT IN (SELECT id FROM academic_year_terms);

-- ---------------------------------------------------------------------------
-- 5. Placeholder half-term breaks for the 2026 terms (gov-issued dates go here)
-- ---------------------------------------------------------------------------
UPDATE academic_year_terms SET half_term_start = '2026-03-13', half_term_end = '2026-03-19' WHERE id = 1;
UPDATE academic_year_terms SET half_term_start = '2026-06-26', half_term_end = '2026-07-02' WHERE id = 2;
UPDATE academic_year_terms SET half_term_start = '2026-10-09', half_term_end = '2026-10-15' WHERE id = 3;
