/* Academic content is inserted through the API without manually assigned ids. */
ALTER TABLE lesson_templates
    MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE lesson_plans
    MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE schemes_of_work
    MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE assessments
    MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE scheme_templates
    MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
