(function () {
  'use strict';
  let status = '';
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = (v) => `KES ${Number(v || 0).toLocaleString()}`;
  const msg = (text, kind = 'success') => { document.getElementById('comMessage').innerHTML = text ? `<div class="alert alert-${kind}">${esc(text)}</div>` : ''; };
  async function load() {
    try {
      const data = await API.commerce.management(status ? {status} : {}), summary = data.summary || {}, engagement = data.engagement || {};
      document.getElementById('comMetrics').innerHTML = [['Orders',summary.orders||0],['Gross value',money(summary.gross_value)],['Discounts',money(summary.discounts_given)],['Net value',money(summary.value)],['Paid',summary.paid_orders||0],['Awaiting collection',summary.awaiting_fulfilment||0],['Physical sales',summary.physical_sales||0],['Wishlist saves',engagement.wishlist_count||0],['Average rating',engagement.average_rating||'—']].map(x => `<article><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('');
      document.getElementById('comOrders').innerHTML = (data.orders || []).map(order => `<article class="commerce-order-card"><header><div><small>${esc(order.order_reference)} · ${esc(order.source)}</small><h3>${esc(order.buyer_name || 'Customer')}</h3></div><span>${esc(order.status.replaceAll('_',' '))}</span></header><div><strong>${money(order.total_amount)}</strong>${Number(order.discount_total||0)>0?`<small class="d-block text-success">Discount ${money(order.discount_total)}</small>`:''}<p>${order.line_count} line(s) · Payment ${esc(order.payment_status)} · ${esc(order.created_at)}</p>${(order.items||[]).map(i=>`<small class="d-block">${i.quantity} × ${esc(i.product_title)} · ${esc(i.variant_name||'Standard')} · ${esc(i.size_label)}</small>`).join('')}</div><footer>${order.payment_status==='paid'&&order.status!=='fulfilled'?['preparing','ready'].filter(x=>x!==order.status).map(x=>`<button class="btn btn-sm btn-outline-success" data-order="${order.id}" data-next="${x}">Mark ${x}</button>`).join(''):''}${order.payment_status==='paid'&&order.source!=='physical'&&order.status!=='fulfilled'?`<a class="btn btn-sm btn-warning" href="home.php?route=uniform_point_of_sale">Scan &amp; dispatch</a>`:''}${['pending_payment','payment_processing'].includes(order.status)?`<button class="btn btn-sm btn-outline-danger" data-order="${order.id}" data-next="cancelled">Cancel</button>`:''}</footer></article>`).join('') || '<div class="catalog-empty">No orders match this view.</div>';
      document.getElementById('comReviews').innerHTML = (data.pending_reviews || []).map(review => `<article><div><strong>${esc(review.product_title)}</strong><span>${'★'.repeat(Number(review.rating))}</span></div><h3>${esc(review.title||review.reviewer_type+' review')}</h3><p>${esc(review.comment||'')}</p><footer><button class="btn btn-success btn-sm" data-review="${review.id}" data-decision="published">Publish</button> <button class="btn btn-outline-danger btn-sm" data-review="${review.id}" data-decision="rejected">Reject</button></footer></article>`).join('') || '<div class="catalog-empty">No reviews await moderation.</div>';
      document.getElementById('comProducts').innerHTML = (data.product_analytics || []).map(product => `<article class="commerce-order-card"><h3>${esc(product.title)}</h3><p><strong>${product.units_sold||0}</strong> sold · <strong>${product.wishlist_count||0}</strong> saves</p><p><strong>${product.available_stock||0}</strong> in stock · <strong>${product.reserved_stock||0}</strong> reserved</p><small>${product.rating?`${product.rating}/5 from ${product.review_count} review(s)`:'Not rated yet'}</small></article>`).join('');
      document.querySelectorAll('[data-order]').forEach(button => button.onclick = async () => { try { await API.commerce.updateOrderStatus(button.dataset.order,{status:button.dataset.next});msg('Order status updated.');load(); } catch(error){msg(error.message,'danger');} });
      document.querySelectorAll('[data-review]').forEach(button => button.onclick = async () => { try { await API.commerce.moderateReview(button.dataset.review,button.dataset.decision);msg('Review moderation saved.');load(); } catch(error){msg(error.message,'danger');} });
    } catch(error) { msg(error.message || 'Unable to load commerce operations','danger'); }
  }
  document.querySelectorAll('#comFilter button').forEach(button=>button.onclick=()=>{status=button.dataset.status;document.querySelectorAll('#comFilter button').forEach(x=>x.classList.toggle('active',x===button));load();});
  document.getElementById('comRefresh').onclick=load;load();
})();
