(function () {
  'use strict';
  let status = '', pos = null, posModal = null;
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = (v) => `KES ${Number(v || 0).toLocaleString()}`;
  const msg = (text, kind = 'success') => { document.getElementById('comMessage').innerHTML = text ? `<div class="alert alert-${kind}">${esc(text)}</div>` : ''; };
  async function load() {
    try {
      const data = await API.commerce.management(status ? {status} : {}), summary = data.summary || {}, engagement = data.engagement || {};
      document.getElementById('comMetrics').innerHTML = [['Orders',summary.orders||0],['Order value',money(summary.value)],['Paid',summary.paid_orders||0],['Awaiting collection',summary.awaiting_fulfilment||0],['Physical sales',summary.physical_sales||0],['Wishlist saves',engagement.wishlist_count||0],['Average rating',engagement.average_rating||'—']].map(x => `<article><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('');
      document.getElementById('comOrders').innerHTML = (data.orders || []).map(order => `<article class="commerce-order-card"><header><div><small>${esc(order.order_reference)} · ${esc(order.source)}</small><h3>${esc(order.buyer_name || 'Customer')}</h3></div><span>${esc(order.status.replaceAll('_',' '))}</span></header><div><strong>${money(order.total_amount)}</strong><p>${order.line_count} line(s) · Payment ${esc(order.payment_status)} · ${esc(order.created_at)}</p>${(order.items||[]).map(i=>`<small class="d-block">${i.quantity} × ${esc(i.product_title)} · ${esc(i.variant_name||'Standard')} · ${esc(i.size_label)}</small>`).join('')}</div><footer>${order.payment_status==='paid'&&order.status!=='fulfilled'?['preparing','ready','fulfilled'].filter(x=>x!==order.status).map(x=>`<button class="btn btn-sm btn-outline-success" data-order="${order.id}" data-next="${x}">Mark ${x}</button>`).join(''):''}${['pending_payment','payment_processing'].includes(order.status)?`<button class="btn btn-sm btn-outline-danger" data-order="${order.id}" data-next="cancelled">Cancel</button>`:''}</footer></article>`).join('') || '<div class="catalog-empty">No orders match this view.</div>';
      document.getElementById('comReviews').innerHTML = (data.pending_reviews || []).map(review => `<article><div><strong>${esc(review.product_title)}</strong><span>${'★'.repeat(Number(review.rating))}</span></div><h3>${esc(review.title||review.reviewer_type+' review')}</h3><p>${esc(review.comment||'')}</p><footer><button class="btn btn-success btn-sm" data-review="${review.id}" data-decision="published">Publish</button> <button class="btn btn-outline-danger btn-sm" data-review="${review.id}" data-decision="rejected">Reject</button></footer></article>`).join('') || '<div class="catalog-empty">No reviews await moderation.</div>';
      document.getElementById('comProducts').innerHTML = (data.product_analytics || []).map(product => `<article class="commerce-order-card"><h3>${esc(product.title)}</h3><p><strong>${product.units_sold||0}</strong> sold · <strong>${product.wishlist_count||0}</strong> saves</p><p><strong>${product.available_stock||0}</strong> in stock · <strong>${product.reserved_stock||0}</strong> reserved</p><small>${product.rating?`${product.rating}/5 from ${product.review_count} review(s)`:'Not rated yet'}</small></article>`).join('');
      document.querySelectorAll('[data-order]').forEach(button => button.onclick = async () => { try { await API.commerce.updateOrderStatus(button.dataset.order,{status:button.dataset.next});msg('Order status updated.');load(); } catch(error){msg(error.message,'danger');} });
      document.querySelectorAll('[data-review]').forEach(button => button.onclick = async () => { try { await API.commerce.moderateReview(button.dataset.review,button.dataset.decision);msg('Review moderation saved.');load(); } catch(error){msg(error.message,'danger');} });
    } catch(error) { msg(error.message || 'Unable to load commerce operations','danger'); }
  }
  async function openPos() {
    try {
      pos=await API.commerce.pointOfSaleOptions();
      document.getElementById('comPosProduct').innerHTML='<option value="">Choose product</option>'+pos.products.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('');
      document.getElementById('comPosBuyer').innerHTML='<option value="">Walk-in customer</option>'+pos.staff.map(s=>`<option value="${s.id}">${esc(s.name+' · '+s.username)}</option>`).join('');
      document.getElementById('comPosPayment').innerHTML=(pos.payment_options||[]).filter(x=>['cash','bank_transfer','cheque'].includes(x.channel)).flatMap(x=>x.accounts.map(a=>`<option value="${x.channel}|${a.id}">${esc(x.label+' · '+a.account_name)}</option>`)).join('')||'<option value="">Configure a uniforms cash/bank/cheque account first</option>';
      document.getElementById('comPosProduct').onchange=renderPosSizes;posModal=bootstrap.Modal.getOrCreateInstance(document.getElementById('comPosModal'));posModal.show();
    } catch(error){msg(error.message,'danger');}
  }
  function renderPosSizes(){const product=pos.products.find(x=>Number(x.id)===Number(document.getElementById('comPosProduct').value));document.getElementById('comPosSize').innerHTML='<option value="">Choose size / variant</option>'+(product?.sizes||[]).filter(x=>Number(x.available)>0).map(x=>`<option value="${x.size_id}" data-variant="${x.variant_id||''}">${esc((x.size_label||x.size)+' · '+money(x.unit_price)+' · '+x.available+' available')}</option>`).join('');}
  document.getElementById('comPosForm').onsubmit=async event=>{event.preventDefault();const payment=document.getElementById('comPosPayment').value.split('|'),size=document.getElementById('comPosSize').selectedOptions[0];try{await API.commerce.pointOfSale({staff_buyer_id:Number(document.getElementById('comPosBuyer').value||0),channel:payment[0],financial_account_id:Number(payment[1]||0),payment_reference:document.getElementById('comPosReference').value,note:document.getElementById('comPosNote').value,items:[{product_id:Number(document.getElementById('comPosProduct').value),variant_id:Number(size?.dataset.variant||0)||null,size_id:Number(size?.value),quantity:Number(document.getElementById('comPosQty').value)}]});posModal.hide();msg('Counter sale completed, stock deducted and revenue recorded.');event.target.reset();load();}catch(error){document.getElementById('comPosMessage').innerHTML=`<div class="alert alert-danger">${esc(error.message)}</div>`;}};
  document.querySelectorAll('#comFilter button').forEach(button=>button.onclick=()=>{status=button.dataset.status;document.querySelectorAll('#comFilter button').forEach(x=>x.classList.toggle('active',x===button));load();});
  document.getElementById('comRefresh').onclick=load;document.getElementById('comPos').onclick=openPos;load();
})();
