const ClassAttendanceHistoryController = {
  async init() { await window.AuthContext?.ready?.(); if (!window.AuthContext?.isAuthenticated()) return; const date = document.getElementById('historyDate'); date.value = new Date().toISOString().slice(0, 10); document.getElementById('historyStream').addEventListener('change', () => this.load()); date.addEventListener('change', () => this.load()); await this.classes(); },
  unwrap(r) { const v = r?.data?.data || r?.data || r || []; return Array.isArray(v) ? v : (v.classes || v.rows || []); },
  async classes() { try { const rows = this.unwrap(await window.API.apiCall('/attendance/classes', 'GET')); const select = document.getElementById('historyStream'); rows.forEach(c => { const o = document.createElement('option'); o.value = c.stream_id; o.textContent = `${c.display_name || c.name} (${c.student_count || 0})`; select.appendChild(o); }); if (rows.length === 1) { select.value = rows[0].stream_id; await this.load(); } } catch (e) { this.message(e.message || 'Unable to load your class streams.', 'danger'); } },
  async load() { const stream = document.getElementById('historyStream').value, date = document.getElementById('historyDate').value; if (!stream || !date) return this.message('Select your class stream and date.', 'warning'); try { const r = await window.API.attendance.getDailyRegister({ stream_id: stream, date }); const rows = Array.isArray(r) ? r : (r?.rows || []); document.getElementById('historyBody').innerHTML = rows.length ? rows.map(x => `<tr><td>${this.esc(x.admission_no)}</td><td>${this.esc([x.first_name, x.last_name].filter(Boolean).join(' '))}</td><td><span class="badge text-bg-${x.status === 'present' ? 'success' : x.status === 'absent' ? 'danger' : 'warning'}">${this.esc(x.status || 'Not marked')}</span></td><td>${this.esc(x.marked_at || '—')}</td><td>${this.esc(x.notes || '—')}</td></tr>`).join('') : '<tr><td colspan="5" class="text-center text-muted py-4">No attendance records for this date.</td></tr>'; } catch (e) { this.message(e.message || 'Unable to load attendance history.', 'danger'); } },
  message(t, type) { const e = document.getElementById('historyMessage'); e.textContent = t; e.className = `alert alert-${type}`; },
  esc(v) { const e = document.createElement('div'); e.textContent = v == null ? '' : String(v); return e.innerHTML; }
};
document.addEventListener('DOMContentLoaded', () => ClassAttendanceHistoryController.init());
