(() => {
  const state={draft:null,staff:[],types:[],year:null,term:null}; const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function init(){await window.AuthContext?.ready();if(window.AcademicContext){if(!AcademicContext.isLoaded())await AcademicContext.init();state.year=AcademicContext.getAcademicYearId();state.term=AcademicContext.getTermId();}try{const [s,t]=await Promise.all([API.apiCall('/staff/staff','GET',null,{limit:1000},{checkPermission:false}),API.attendance.getDutyTypes()]);state.staff=s?.staff||s?.data?.staff||s?.data||[];state.types=t?.data||t||[];}catch(e){} $('newDutyDraft').onclick=()=>open();$('addDutyRow').onclick=()=>addRow();$('saveDutyDraft').onclick=()=>save(false);$('submitDutyDraft').onclick=()=>save(true);await load();}
  async function load(){const r=await API.schedules.listDutyRosterDrafts();const rows=r?.data||r||[];$('dutyDraftRows').innerHTML=rows.map(d=>`<tr><td>${esc(d.title)}</td><td>${esc(d.start_date)} – ${esc(d.end_date)}</td><td>${d.entry_count||0}</td><td><span class="badge bg-${d.status==='published'?'success':d.status==='approved'?'primary':'secondary'}">${esc(d.status)}</span></td><td>${esc(d.updated_at)}</td><td><button class="btn btn-sm btn-outline-success" onclick="dutyRoster.open(${d.id})">Open</button></td></tr>`).join('')||'<tr><td colspan="6" class="text-center py-4 text-muted">No duty drafts</td></tr>';}
  function opts(items,value,label){return '<option value="">Select</option>'+items.map(x=>`<option value="${x.id}" ${String(x.id)===String(value||'')?'selected':''}>${esc(label(x))}</option>`).join('');}
  function addRow(e={}){const tr=document.createElement('tr');tr.innerHTML=`<td><input class="form-control form-control-sm d-date" type="date" value="${esc(e.date)}"></td><td><select class="form-select form-select-sm d-staff">${opts(state.staff,e.staff_id,x=>`${x.first_name||''} ${x.last_name||''}`.trim()||x.name)}</select></td><td><select class="form-select form-select-sm d-type">${opts(state.types,e.duty_type_id,x=>x.duty_name||x.name)}</select></td><td><select class="form-select form-select-sm d-shift"><option>full_day</option><option>morning</option><option>afternoon</option><option>evening</option><option>night</option></select></td><td><div class="d-flex gap-1"><input class="form-control form-control-sm d-start" type="time" value="${esc(e.start_time)}"><input class="form-control form-control-sm d-end" type="time" value="${esc(e.end_time)}"></div></td><td><input class="form-control form-control-sm d-location" value="${esc(e.location)}"></td><td><select class="form-select form-select-sm d-swap">${opts(state.staff,e.swapped_with_id,x=>`${x.first_name||''} ${x.last_name||''}`.trim()||x.name)}</select></td><td><button class="btn btn-sm btn-outline-danger d-remove">×</button></td>`;tr.querySelector('.d-shift').value=e.shift||'full_day';tr.querySelector('.d-remove').onclick=()=>tr.remove();$('dutyEntryRows').appendChild(tr);}
  function open(id=null){state.draft=null;$('dutyTitle').value='Teacher-on-duty roster';$('dutyStart').value='';$('dutyEnd').value='';$('dutyEntryRows').innerHTML='';$('dutyStatus').textContent='New draft';if(id)API.schedules.getDutyRosterDraft(id).then(r=>{const d=r?.data||r;state.draft=d;$('dutyTitle').value=d.title;$('dutyStart').value=d.start_date;$('dutyEnd').value=d.end_date;$('dutyStatus').textContent=`Draft #${d.id} · ${d.status}`;(d.entries||[]).forEach(addRow);});else addRow();new bootstrap.Modal($('dutyDraftModal')).show();}
  async function save(submit){const entries=[...$('dutyEntryRows').querySelectorAll('tr')].map(tr=>({date:tr.querySelector('.d-date').value,staff_id:tr.querySelector('.d-staff').value,duty_type_id:tr.querySelector('.d-type').value,shift:tr.querySelector('.d-shift').value,start_time:tr.querySelector('.d-start').value||null,end_time:tr.querySelector('.d-end').value||null,location:tr.querySelector('.d-location').value,swapped_with_id:tr.querySelector('.d-swap').value||0}));const r=await API.schedules.saveDutyRosterDraft({id:state.draft?.id,academic_year_id:state.year,academic_year_term_id:state.term,title:$('dutyTitle').value,start_date:$('dutyStart').value,end_date:$('dutyEnd').value,entries});const d=r?.data||r;state.draft={id:d.id};if(submit)await API.schedules.transitionDutyRosterDraft({id:d.id,action:'submit'});$('dutyStatus').textContent=`Draft #${d.id} · ${submit?'submitted':'saved'}`;await load();}
  function printRoster(){if(window.PrintManager)PrintManager.printElement('dutyDraftTable',{title:'Teacher-on-Duty Roster',orientation:'landscape',paperSize:'A4'});else window.print();}
  window.dutyRoster={open,printRoster};document.addEventListener('DOMContentLoaded',init);
})();
