(function(){'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>`KES ${Number(v||0).toLocaleString()}`;let state={cart:{items:[]},wish:[],orders:[],paymentOptions:[]};
 const msg=(t,k='success')=>document.getElementById('icaMessage').innerHTML=t?`<div class="alert alert-${k}">${esc(t)}</div>`:'';
 async function load(){try{const [cart,wish,orders,payments]=await Promise.all([API.commerce.cart(),API.commerce.wishlist(),API.commerce.orders(),API.commerce.paymentOptions()]);state={cart,wish:wish.items||wish,orders:orders.orders||orders,paymentOptions:payments.options||[]};render()}catch(e){msg(e.message||'Unable to load your shopping account','danger')}}
 function render(){const paymentChoices=state.paymentOptions.map(x=>`<option value="${esc(x.channel)}" data-account="${Number(x.accounts?.[0]?.id||0)}">${esc(x.label)}</option>`).join('');document.getElementById('icaCartBadge').textContent=state.cart.count||0;document.getElementById('icaCart').innerHTML=state.cart.items.length?`<div class="catalog-account-layout"><div class="catalog-lines">${state.cart.items.map(x=>`<article><img src="${esc(x.image_url)}" alt=""><div><h3>${esc(x.title)}</h3><p>${esc(x.variant_name||'Standard')} · ${esc(x.size_label||x.size)}</p><strong>${money(x.line_total)}</strong></div><label>Qty<input type="number" min="1" max="20" value="${x.quantity}" data-qty="${x.id}"></label><button class="btn btn-link text-danger" data-remove="${x.id}">Remove</button></article>`).join('')}</div><aside class="catalog-checkout"><small>Order total</small><h2>${money(state.cart.total)}</h2><label>Payment method<select id="icaChannel" class="form-select">${paymentChoices||'<option value="">No configured online payment channel</option>'}</select></label><label>Phone number<input id="icaPhone" class="form-control" placeholder="07XX XXX XXX"></label><label>Order note<textarea id="icaNote" class="form-control" rows="2"></textarea></label><button id="icaCheckout" class="btn btn-success btn-lg w-100" ${paymentChoices?'':'disabled'}>Place order &amp; pay</button><small>Stock is reserved once the order is placed and deducted when payment is confirmed.</small></aside></div>`:'<div class="catalog-empty"><h3>Your cart is empty</h3><p>Products you select will appear here.</p></div>';
 document.getElementById('icaWishlist').innerHTML=state.wish.length?`<div class="catalog-wishlist-grid">${state.wish.map(x=>`<article><img src="${esc(x.image_url)}"><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p><a class="btn btn-success" href="home.php?route=internal_product_details&id=${x.product_id}">Choose options</a><button class="btn btn-link text-danger" data-wremove="${x.product_id}">Remove</button></article>`).join('')}</div>`:'<div class="catalog-empty">Your wishlist is empty.</div>';
 document.getElementById('icaOrders').innerHTML=state.orders.length?`<div class="catalog-orders-list">${state.orders.map(o=>`<article><header><div><small>${esc(o.order_reference)}</small><h3>${esc(o.status.replaceAll('_',' '))}</h3></div><strong>${money(o.total_amount)}</strong></header>${o.items.map(i=>`<p>${i.quantity} × ${esc(i.product_title)} · ${esc(i.variant_name||'Standard')} · ${esc(i.size_label)}</p>`).join('')}<footer><span>Payment: ${esc(o.payment_status)}</span>${['pending_payment','payment_processing'].includes(o.status)?`<span><button class="btn btn-outline-success btn-sm" data-retry="${o.id}">Retry payment</button> <button class="btn btn-outline-danger btn-sm" data-cancel="${o.id}">Cancel</button></span>`:''}</footer></article>`).join('')}</div>`:'<div class="catalog-empty">You have not placed any orders.</div>';
 bind();}
 function bind(){document.querySelectorAll('[data-qty]').forEach(x=>x.onchange=async()=>{try{await API.commerce.updateCart(x.dataset.qty,Number(x.value));await load()}catch(e){msg(e.message,'danger')}});document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=async()=>{await API.commerce.removeCart(x.dataset.remove);load()});document.querySelectorAll('[data-wremove]').forEach(x=>x.onclick=async()=>{await API.commerce.removeWishlist(x.dataset.wremove);load()});document.querySelectorAll('[data-cancel]').forEach(x=>x.onclick=async()=>{try{await API.commerce.cancelOrder(x.dataset.cancel);msg('Order cancelled and reserved stock released.');load()}catch(e){msg(e.message,'danger')}});document.querySelectorAll('[data-retry]').forEach(x=>x.onclick=async()=>{const option=state.paymentOptions[0];if(!option)return msg('No online collection account is configured.','warning');try{await API.commerce.retryPayment(x.dataset.retry,{channel:option.channel,financial_account_id:Number(option.accounts?.[0]?.id||0),phone:prompt('M-Pesa phone number:','')||''});msg('Payment request restarted.');load()}catch(e){msg(e.message,'danger')}});const c=document.getElementById('icaCheckout');if(c)c.onclick=checkout;}
 async function checkout(){const phone=document.getElementById('icaPhone').value.trim(),select=document.getElementById('icaChannel');if(!phone)return msg('Enter the M-Pesa phone number.','warning');try{const r=await API.commerce.checkout({channel:select.value,financial_account_id:Number(select.selectedOptions[0]?.dataset.account||0),phone,note:document.getElementById('icaNote').value});msg(`Order ${r.order.order_reference} was placed. Complete the payment prompt on your phone.`);await load()}catch(e){msg(e.message||'Checkout failed','danger')}}
 document.querySelectorAll('.catalog-account-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.catalog-account-tabs button').forEach(x=>x.classList.toggle('active',x===b));['cart','wishlist','orders'].forEach(n=>document.getElementById(`ica${n[0].toUpperCase()+n.slice(1)}`).classList.toggle('d-none',n!==b.dataset.tab))});load();
})();
