(function(){'use strict';
  const root=document.querySelector('.catalog-detail-page');if(!root)return;
  const id=Number(root.dataset.productId);const base=String(window.APP_BASE||'').replace(/\/+$/,'');
  const state={product:null,variantId:null,sizeId:null,imageIndex:0};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>`KES ${Number(v||0).toLocaleString()}`;
  const message=(text,type='success')=>document.getElementById('icdMessage').innerHTML=text?`<div class="alert alert-${type}">${esc(text)}</div>`:'';
  function images(){const p=state.product;const related=p.images.filter(x=>state.variantId&&Number(x.variant_id)===state.variantId);return related.length?related:p.images.filter(x=>!x.variant_id).length?p.images.filter(x=>!x.variant_id):[{url:p.image_url}];}
  function sizes(){return state.product.sizes.filter(x=>state.variantId?Number(x.variant_id)===state.variantId:!x.variant_id);}
  function render(){const p=state.product, ims=images();if(state.imageIndex>=ims.length)state.imageIndex=0;const selected=sizes().find(x=>Number(x.size_id)===state.sizeId);const inStock=selected&&Number(selected.available)>0;
    document.getElementById('icdProduct').innerHTML=`<section class="catalog-detail-gallery"><img class="catalog-detail-main-image" src="${esc(ims[state.imageIndex]?.url||p.image_url)}" alt="${esc(p.title)}"><div class="catalog-detail-thumbs">${ims.map((x,i)=>`<button class="${i===state.imageIndex?'active':''}" data-image="${i}"><img src="${esc(x.url)}" alt="${esc(x.alt_text||p.title)}"></button>`).join('')}</div></section>
    <section class="catalog-detail-copy"><small>${esc(p.category_slug||'Kingsway collection')}</small><h1>${esc(p.title)}</h1><p>${esc(p.description||'')}</p>
    ${p.variants.length?`<h3>Choose a colour or variant</h3><div class="catalog-detail-options">${p.variants.map(v=>`<button class="${Number(v.id)===state.variantId?'active':''}" data-variant="${v.id}"><i style="background:${esc(v.swatch_hex||'#0b5d3b')}"></i>${esc(v.name||v.color_name)}</button>`).join('')}</div>`:''}
    <h3>Choose a size</h3><div class="catalog-detail-sizes">${sizes().map(s=>`<button class="${Number(s.size_id)===state.sizeId?'active':''}" data-size="${s.size_id}" ${Number(s.available)<1?'disabled':''}>${esc(s.size_label||s.size)}<small>${Number(s.available)>0?`${money(s.unit_price)} · ${s.available} available`:'Out of stock'}</small></button>`).join('')||'<p class="text-muted">Sizes have not been published.</p>'}</div>
    <div class="catalog-detail-buy"><label>Quantity<input class="form-control" id="icdQty" type="number" value="1" min="1" max="20"></label><div><strong>${selected?money(selected.unit_price):'Select a size'}</strong><small>${inStock?'Ready to order':'Coming Soon / unavailable'}</small></div></div>
    <div class="catalog-detail-actions"><button class="btn btn-success btn-lg" id="icdAdd" ${!inStock?'disabled':''}><i class="bi bi-bag-plus"></i> Add to cart</button><button class="btn btn-outline-dark btn-lg" id="icdWish"><i class="bi bi-heart"></i> Save to wishlist</button></div></section>`;
    document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{state.imageIndex=Number(b.dataset.image);render()});document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>{state.variantId=Number(b.dataset.variant);state.sizeId=null;state.imageIndex=0;render()});document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{state.sizeId=Number(b.dataset.size);render()});
    document.getElementById('icdAdd').onclick=addCart;document.getElementById('icdWish').onclick=addWish;renderReviews();
  }
  function renderReviews(){const list=state.product.reviews||[];document.getElementById('icdReviews').innerHTML=list.map(r=>`<article><div><strong>${esc(r.reviewer_name)}</strong><span>${'★'.repeat(Number(r.rating))}${'☆'.repeat(5-Number(r.rating))}</span></div><h3>${esc(r.title||'Product review')}</h3><p>${esc(r.comment||'')}</p><small>${r.verified_purchase?'Verified purchase · ':''}${esc(r.created_at)}</small></article>`).join('')||'<div class="catalog-empty">No published reviews yet. Be the first to share useful feedback.</div>'}
  async function addCart(){try{const quantity=Number(document.getElementById('icdQty').value||1);const cart=await API.commerce.addCart({product_id:id,variant_id:state.variantId,size_id:state.sizeId,quantity});document.getElementById('icdCartCount').textContent=cart.count||0;message('Product added to your cart.')}catch(e){message(e.message||'Unable to add to cart','danger')}}
  async function addWish(){try{await API.commerce.addWishlist(id);message('Product saved to your wishlist.')}catch(e){message(e.message||'Unable to save product','danger')}}
  async function init(){if(!id){message('A valid product is required.','danger');return}try{state.product=await API.commerce.product(id);state.variantId=Number(state.product.variants.find(x=>Number(x.is_default))?.id||state.product.variants[0]?.id||0)||null;const c=await API.commerce.cart();document.getElementById('icdCartCount').textContent=c.count||0;render()}catch(e){message(e.message||'Unable to load product','danger')}}
  document.getElementById('icdReviewToggle').onclick=()=>document.getElementById('icdReviewForm').classList.toggle('d-none');document.getElementById('icdReviewForm').onsubmit=async e=>{e.preventDefault();try{await API.commerce.review({product_id:id,rating:Number(document.getElementById('icdRating').value),title:document.getElementById('icdReviewTitle').value,comment:document.getElementById('icdReviewComment').value});e.target.reset();e.target.classList.add('d-none');message('Your review was submitted and is awaiting moderation.')}catch(x){message(x.message||'Unable to submit review','danger')}};init();
})();
