const paymentIntegrationSettingsController = {
  rows: [], options: {}, modal: null, permissionsModal: null, permissionAccountId: 0,
  esc(v) { const d=document.createElement('div'); d.textContent=String(v??''); return d.innerHTML; },
  async init() { await window.AuthContext?.ready(); this.modal = new bootstrap.Modal(document.getElementById('pisModal')); this.permissionsModal = new bootstrap.Modal(document.getElementById('pisPermissionsModal')); document.getElementById('pisNew')?.addEventListener('click',()=>this.open()); document.getElementById('pisForm')?.addEventListener('submit',e=>{e.preventDefault();this.save();}); document.getElementById('pisPermissionsSave')?.addEventListener('click',()=>this.savePermissions()); await this.loadOptions(); await this.load(); },
  async loadOptions() { const r=await window.API.finance.getFinancialAccountSetupOptions(); this.options=r?.data||r||{}; this.fill('pisKind',this.options.kinds||[],'code','name'); this.fill('pisProvider',this.options.providers||[],'code','display_name',true); this.fill('pisLedger',this.options.ledger_accounts||[],'account_code',x=>`${x.account_code} · ${x.account_name}`); this.fill('pisPurposes',this.options.purposes||[],'code','name'); this.fill('pisChannels',this.options.channels||[],'code','name'); },
  fill(id,rows,value,label,optional=false) { const s=document.getElementById(id); if(!s)return; const first=optional?'<option value="">None/manual</option>':''; s.innerHTML=first+rows.map(x=>`<option value="${this.esc(x[value])}">${this.esc(typeof label==='function'?label(x):x[label])}</option>`).join(''); },
  async load() { const r=await window.API.finance.getFinancialAccounts(); this.rows=(r?.data||r||{}).accounts||[]; document.getElementById('pisBody').innerHTML=this.rows.map((x,i)=>`<tr><td>${this.esc(x.account_name)}</td><td>${this.esc(x.account_kind)} / ${this.esc(x.provider_code||'manual')}</td><td><code>${this.esc(x.account_identifier)}</code></td><td>${this.esc(x.ledger_code||'—')}</td><td>${this.esc(x.purposes||'')}</td><td>${this.esc(x.channels||'')}</td><td><span class="badge ${x.status==='active'?'bg-success':'bg-warning text-dark'}">${this.esc(x.status)}</span></td><td><button class="btn btn-sm btn-outline-primary" data-edit="${i}">Edit</button> <button class="btn btn-sm btn-outline-secondary" data-perms="${x.id}">Permissions</button> ${x.status==='pending_verification'?`<button class="btn btn-sm btn-outline-success" data-verify="${x.id}">Verify</button>`:''}</td></tr>`).join('')||'<tr><td colspan="8" class="text-center text-muted py-4">No configured accounts.</td></tr>'; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>this.open(this.rows[Number(b.dataset.edit)])); document.querySelectorAll('[data-verify]').forEach(b=>b.onclick=()=>this.verify(Number(b.dataset.verify))); document.querySelectorAll('[data-perms]').forEach(b=>b.onclick=()=>this.openPermissions(Number(b.dataset.perms))); },
  open(row=null) { document.getElementById('pisForm').reset(); document.getElementById('pisId').value=row?.id||''; if(row){['Name','Identifier','Bank','Currency'].forEach(n=>document.getElementById('pis'+n).value=row[{Name:'account_name',Identifier:'account_identifier',Bank:'bank_name',Currency:'currency'}[n]]||'');document.getElementById('pisKind').value=row.account_kind||'';document.getElementById('pisProvider').value=row.provider_code||'';document.getElementById('pisLedger').value=row.ledger_code||'';this.select('pisPurposes',row.purposes);this.select('pisChannels',row.channels);} this.modal.show(); },
  select(id,value){const vals=String(value||'').split(',');document.querySelectorAll(`#${id} option`).forEach(o=>o.selected=vals.includes(o.value));},
  async save(){const data={account_name:pisName.value,account_kind:pisKind.value,provider_code:pisProvider.value,account_identifier:pisIdentifier.value,bank_name:pisBank.value,currency:pisCurrency.value,ledger_code:pisLedger.value,purposes:[...pisPurposes.selectedOptions].map(x=>x.value),channels:[...pisChannels.selectedOptions].map(x=>x.value)};try{const id=Number(pisId.value);if(id)await window.API.finance.updateFinancialAccount(id,data);else await window.API.finance.createFinancialAccount(data);this.modal.hide();await this.load();}catch(e){document.getElementById('pisMessage').innerHTML=`<div class="alert alert-danger">${this.esc(e.message||'Unable to save account')}</div>`;}},
  async verify(id){if(!confirm('Verify and activate this account?'))return;try{await window.API.finance.verifyFinancialAccount(id,'active');await this.load();}catch(e){alert(e.message||'Unable to verify account');}}
  ,async openPermissions(id){this.permissionAccountId=id;const r=await window.API.finance.getFinancialAccountPermissions(id);const rows=(r?.data||r||{}).permissions||[];document.getElementById('pisPermissionsBody').innerHTML=rows.map(x=>`<div class="row align-items-center border-bottom py-2"><div class="col">${this.esc(x.name)}</div><div class="col-auto"><label class="form-check"><input class="form-check-input pis-receive" type="checkbox" data-role="${x.role_id}" ${Number(x.can_receive)?'checked':''}> Receive</label></div><div class="col-auto"><label class="form-check"><input class="form-check-input pis-disburse" type="checkbox" data-role="${x.role_id}" ${Number(x.can_disburse)?'checked':''}> Disburse</label></div></div>`).join('');this.permissionsModal.show();},
  async savePermissions(){const permissions=[...document.querySelectorAll('.pis-receive')].map(x=>({role_id:Number(x.dataset.role),can_receive:x.checked?1:0,can_disburse:document.querySelector(`.pis-disburse[data-role="${x.dataset.role}"]`)?.checked?1:0}));try{await window.API.finance.setFinancialAccountPermissions(this.permissionAccountId,permissions);this.permissionsModal.hide();}catch(e){alert(e.message||'Unable to save permissions');}}
}; window.paymentIntegrationSettingsController=paymentIntegrationSettingsController; document.addEventListener('DOMContentLoaded',()=>paymentIntegrationSettingsController.init().catch(e=>{document.getElementById('pisMessage').innerHTML=`<div class="alert alert-danger">${paymentIntegrationSettingsController.esc(e.message)}</div>`;}));
