const studentFundTransfersController = {
  sources: [], students: [],
  esc(v) { const d=document.createElement('div'); d.textContent=String(v ?? ''); return d.innerHTML; },
  notify(m,t='success') { if (window.showNotification) showNotification(m,t); else alert(m); },
  async init() { await window.AuthContext?.ready(); document.getElementById('fundTransferRefresh')?.addEventListener('click',()=>this.load()); document.getElementById('fundTransferForm')?.addEventListener('submit',e=>{e.preventDefault();this.submit();}); document.getElementById('fundDestinationType')?.addEventListener('change',()=>this.renderDestinationEntitlements()); await this.loadSources(); await this.loadStudents(); await this.load(); },
  async loadSources() { const r=await window.API.finance.getStudentFundSources(); this.sources=r?.data?.sources||[]; const s=document.getElementById('fundSource'); s.innerHTML=this.sources.map((x,i)=>`<option value="${i}">${this.esc(x.student_name)} · ${this.esc(x.account_type)} · ${this.esc(x.reference)} · KES ${Number(x.available_amount).toLocaleString()}</option>`).join('')||'<option>No available credit</option>'; this.renderDestinationEntitlements(); },
  async loadStudents() { const r=await window.API.students.getAll({limit:1000,status:'active'}); this.students=r?.data||[]; document.getElementById('fundDestinationStudent').innerHTML='<option value="">Select student</option>'+this.students.map(x=>`<option value="${x.id}">${this.esc(`${x.admission_no||''} — ${x.first_name||''} ${x.last_name||''}`)}</option>`).join(''); },
  renderDestinationEntitlements() { const transport=this.sources.filter(x=>x.account_type==='transport'); const wrap=document.getElementById('fundDestinationTransportWrap'); wrap.classList.toggle('d-none',document.getElementById('fundDestinationType').value!=='transport'); document.getElementById('fundDestinationTransport').innerHTML=transport.map(x=>`<option value="${x.source_id}">${this.esc(x.student_name)} · ${this.esc(x.reference)}</option>`).join('')||'<option>No transport coverage</option>'; },
  async load() { const r=await window.API.finance.listStudentFundTransfers(); const rows=r?.data?.transfers||[]; document.getElementById('fundTransferBody').innerHTML=rows.map(x=>`<tr><td>${this.esc(x.source_student_name)} · ${this.esc(x.source_account_type)}</td><td>${this.esc(x.destination_student_name)} · ${this.esc(x.destination_account_type)}</td><td>KES ${Number(x.amount).toLocaleString()}</td><td>${this.esc(x.parent_request_reference||'—')}</td><td><span class="badge bg-${x.status==='posted'?'success':x.status==='rejected'?'danger':'warning'}">${this.esc(x.status)}</span></td><td>${x.status==='pending_approval'?`<button class="btn btn-sm btn-success me-1" data-action="approve" data-id="${x.id}">Approve</button><button class="btn btn-sm btn-outline-danger" data-action="reject" data-id="${x.id}">Reject</button>`:x.status==='approved'?`<button class="btn btn-sm btn-primary" data-action="post" data-id="${x.id}">Post</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="text-center text-muted py-4">No transfer requests.</td></tr>'; document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>this.action(b.dataset.action,b.dataset.id))); },
  async action(action,id) { try { if(action==='post') await window.API.finance.postStudentFundTransfer(id); else await window.API.finance.decideStudentFundTransfer(id,action); this.notify('Transfer updated'); await this.load(); } catch(e) { this.notify(e.message||'Transfer action failed','danger'); } },
  async submit() { const source=this.sources[Number(document.getElementById('fundSource').value)]; const type=document.getElementById('fundDestinationType').value; if(!source) return this.notify('Select an available source credit','warning'); const data={parent_id:source.parent_id||null,source_student_id:Number(source.student_id),source_account_type:source.account_type,source_credit_note_id:source.account_type==='fees'?Number(source.source_id):null,source_entitlement_id:source.account_type==='transport'?Number(source.source_id):null,destination_student_id:Number(document.getElementById('fundDestinationStudent').value),destination_account_type:type,destination_entitlement_id:type==='transport'?Number(document.getElementById('fundDestinationTransport').value):null,amount:Number(document.getElementById('fundAmount').value),parent_request_reference:document.getElementById('fundParentReference').value,reason:document.getElementById('fundReason').value}; try { await window.API.finance.createStudentFundTransfer(data); this.notify('Transfer submitted for approval'); bootstrap.Modal.getInstance(document.getElementById('fundTransferModal'))?.hide(); document.getElementById('fundTransferForm').reset(); await this.load(); } catch(e) { this.notify(e.message||'Transfer request failed','danger'); } }
}; window.studentFundTransfersController=studentFundTransfersController; document.addEventListener('DOMContentLoaded',()=>studentFundTransfersController.init().catch(e=>studentFundTransfersController.notify(e.message||'Unable to load transfers','danger')));
