(function(){'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>`KES ${Number(v||0).toLocaleString()}`;let options=null,scanned=new Map(),selectedOrder=0,packing=null;
 const message=(text,type='success')=>{document.getElementById('posMessage').innerHTML=text?`<div class="alert alert-${type} mt-3">${esc(text)}</div>`:'';};
 async function init(){try{options=await API.commerce.pointOfSaleOptions();const payments=(options.payment_options||[]).filter(p=>['cash','bank_transfer','cheque'].includes(p.channel)).flatMap(p=>p.accounts.map(a=>`<option value="${p.channel}|${a.id}">${esc(p.label)} · ${esc(a.account_name)}</option>`));document.getElementById('posPayment').innerHTML=payments.join('')||'<option value="">Configure a uniforms receiving account</option>';document.getElementById('posBuyer').innerHTML='<option value="">Walk-in customer</option>'+options.staff.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.username)}</option>`).join('');document.getElementById('posStudent').innerHTML='<option value="">Not assigned to a learner</option>'+(options.students||[]).map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.admission_no)}</option>`).join('');await loadOrders();}catch(e){message(e.message,'danger');}}
 function renderLines(){const lines=[...scanned.values()];document.getElementById('posLines').innerHTML=lines.map(u=>`<article class="scan-line"><div><strong>${esc(u.product_title)}</strong><small>${esc(u.variant_name||'Standard')} · ${esc(u.size_label)} · ${money(u.unit_price)}</small><code>${esc(u.unit_code)}</code></div><button type="button" class="btn btn-sm btn-outline-danger" data-remove-unit="${esc(u.unit_code)}"><i class="bi bi-x"></i></button></article>`).join('')||'<div class="empty-state">No products scanned.</div>';document.getElementById('posCount').textContent=String(lines.length);document.getElementById('posGross').textContent=money(lines.reduce((sum,u)=>sum+Number(u.unit_price||0),0));document.getElementById('posComplete').disabled=!lines.length;document.querySelectorAll('[data-remove-unit]').forEach(b=>b.onclick=()=>{scanned.delete(b.dataset.removeUnit);renderLines();});}
 async function scanCounter(code){code=code.trim();if(!code)return;if(scanned.has(code.toUpperCase()))throw new Error('This unit is already in the sale');const unit=await API.commerce.lookupStockUnit(code,'uniform-pos');if(unit.status!=='in_stock')throw new Error(`${unit.unit_code} is ${unit.status.replaceAll('_',' ')}`);scanned.set(unit.unit_code,unit);renderLines();}
 async function submitSale(event){event.preventDefault();const pay=document.getElementById('posPayment').value.split('|');try{const order=await API.commerce.pointOfSale({unit_codes:[...scanned.keys()],staff_buyer_id:Number(document.getElementById('posBuyer').value||0),student_id:Number(document.getElementById('posStudent').value||0)||null,channel:pay[0],financial_account_id:Number(pay[1]||0),payment_reference:document.getElementById('posReference').value,discount_code:document.getElementById('posDiscount').value,note:document.getElementById('posNote').value,scanner_reference:'uniform-pos'});message(`Sale ${order.order_reference} completed for ${money(order.total_amount)}.`);scanned.clear();event.target.reset();renderLines();await init();}catch(e){message(e.message,'danger');}}
 async function loadOrders(){const data=await API.commerce.management();const orders=(data.orders||[]).filter(o=>o.payment_status==='paid'&&o.source!=='physical'&&!['fulfilled','cancelled','refunded'].includes(o.status));document.getElementById('dispatchOrders').innerHTML=orders.map(o=>`<button type="button" class="unit-card text-start" data-pack-order="${o.id}"><span><strong>${esc(o.order_reference)}</strong><small class="d-block">${esc(o.buyer_name||'Customer')} · ${o.line_count} line(s) · ${money(o.total_amount)}</small></span><span class="status-pill ${esc(o.status)}">${esc(o.status)}</span></button>`).join('')||'<div class="empty-state">No paid orders await dispatch.</div>';document.querySelectorAll('[data-pack-order]').forEach(b=>b.onclick=()=>selectOrder(Number(b.dataset.packOrder)));}
 async function selectOrder(id){selectedOrder=id;packing=await API.commerce.orderPacking(id);renderPacking();document.getElementById('dispatchScan').disabled=false;document.getElementById('dispatchScan').focus();}
 function renderPacking(){if(!packing)return;document.getElementById('dispatchSelected').innerHTML=`<strong>${esc(packing.order_reference)}</strong><p>${packing.scanned_units} of ${packing.required_units} units scanned</p>${(packing.packing_lines||[]).map(l=>`<div class="d-flex justify-content-between"><span>${esc(l.product_title)} · ${esc(l.variant_name||'Standard')} · ${esc(l.size_label)}</span><strong>${l.scanned}/${l.quantity}</strong></div>`).join('')}`;document.getElementById('dispatchComplete').disabled=!packing.complete;}
 async function scanDispatch(code){if(!selectedOrder)throw new Error('Select an order first');packing=await API.commerce.scanOrderUnit(selectedOrder,{unit_code:code,scanner_reference:'uniform-dispatch'});renderPacking();}
 document.querySelectorAll('[data-pos-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-pos-tab]').forEach(x=>x.classList.toggle('active',x===b));const counter=b.dataset.posTab==='counter';document.getElementById('posCounter').hidden=!counter;document.getElementById('posDispatch').hidden=counter;});
 document.getElementById('posScan').addEventListener('keydown',async e=>{if(e.key!=='Enter')return;e.preventDefault();const value=e.target.value;e.target.value='';try{await scanCounter(value);}catch(error){message(error.message,'danger');}});document.getElementById('dispatchScan').addEventListener('keydown',async e=>{if(e.key!=='Enter')return;e.preventDefault();const value=e.target.value;e.target.value='';try{await scanDispatch(value);}catch(error){message(error.message,'danger');}});document.getElementById('dispatchComplete').onclick=async()=>{try{const result=await API.commerce.dispatchOrder(selectedOrder,{note:'Released through scanner terminal'});message(`Order ${result.order_reference} dispatched with complete unit traceability.`);selectedOrder=0;packing=null;document.getElementById('dispatchSelected').innerHTML='<div class="empty-state">Select a paid order.</div>';document.getElementById('dispatchScan').disabled=true;document.getElementById('dispatchComplete').disabled=true;await loadOrders();}catch(e){message(e.message,'danger');}};document.getElementById('posForm').onsubmit=submitSale;document.getElementById('posRefresh').onclick=init;renderLines();init();
})();
