<?php
$appBase = rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '')), '/');
if ($appBase === '.') $appBase = '';
?>
<link rel="stylesheet" href="<?= htmlspecialchars($appBase) ?>/css/pages/product-catalog.css?v=<?= asset_version('css/pages/product-catalog.css') ?>">
<div class="commerce-ops-page">
  <header class="commerce-ops-head"><div><small>Uniform store operations</small><h1>Orders, fulfilment &amp; customer activity</h1><p>Monitor online, internal and physical-counter orders from payment through collection.</p></div><div><button class="btn btn-warning me-2" id="comPos"><i class="bi bi-receipt"></i> New counter sale</button><button class="btn btn-light" id="comRefresh"><i class="bi bi-arrow-clockwise"></i> Refresh</button></div></header>
  <div id="comMessage"></div>
  <section id="comMetrics" class="commerce-metrics"></section>
  <nav class="commerce-filter" id="comFilter"><button class="active" data-status="">All</button><button data-status="pending_payment">Payment pending</button><button data-status="paid">Paid</button><button data-status="preparing">Preparing</button><button data-status="ready">Ready</button><button data-status="fulfilled">Fulfilled</button></nav>
  <section id="comOrders" class="commerce-order-board"></section>
  <section class="mt-5"><div class="catalog-reviews-heading"><div><small>Moderation queue</small><h2>Customer reviews</h2></div></div><div id="comReviews" class="catalog-review-grid"></div></section>
  <section class="mt-5"><div class="catalog-reviews-heading"><div><small>Product intelligence</small><h2>Demand &amp; engagement</h2></div></div><div id="comProducts" class="commerce-order-board"></div></section>
</div>
<div class="modal fade" id="comPosModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" id="comPosForm"><div class="modal-header"><div><small>Physical point of sale</small><h3 class="modal-title">Record a counter purchase</h3></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Product</label><select class="form-select" id="comPosProduct" required></select></div><div class="col-md-6"><label class="form-label">Size / variant</label><select class="form-select" id="comPosSize" required></select></div><div class="col-md-4"><label class="form-label">Quantity</label><input class="form-control" id="comPosQty" type="number" min="1" value="1" required></div><div class="col-md-8"><label class="form-label">Staff buyer (optional)</label><select class="form-select" id="comPosBuyer"><option value="">Walk-in customer</option></select></div><div class="col-md-6"><label class="form-label">Payment / receiving account</label><select class="form-select" id="comPosPayment" required></select></div><div class="col-md-6"><label class="form-label">Payment reference</label><input class="form-control" id="comPosReference" placeholder="Receipt, bank or cheque reference"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" id="comPosNote" rows="2"></textarea></div></div><div id="comPosMessage" class="mt-3"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-success">Complete sale &amp; deduct stock</button></div></form></div></div>
<?php asset_script($appBase, 'js/pages/catalog_orders_management.js'); ?>
