<div class="container-fluid py-4" id="supplierPaymentsPage">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <div><h3 class="mb-1"><i class="bi bi-wallet2 me-2 text-primary"></i>Supplier Payments</h3><p class="text-muted mb-0">Select approved liabilities, choose a verified payout account, and submit one or many payments.</p></div>
    <button class="btn btn-outline-secondary" id="spRefresh"><i class="bi bi-arrow-clockwise me-1"></i>Refresh</button>
  </div>
  <div class="row g-3 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Open liabilities</small><h3 id="spCount">0</h3></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Outstanding</small><h3 id="spOutstanding">KES 0.00</h3></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Selected</small><h3 id="spSelected">0 · KES 0.00</h3></div></div></div></div>
  <div class="alert alert-info py-2 small"><i class="bi bi-shield-check me-1"></i>Only bank accounts and M-Pesa numbers marked <strong>verified</strong> are available for payment.</div>
  <div class="card border-0 shadow-sm mb-3"><div class="card-body"><label class="form-label fw-semibold" for="spSourceAccount">Pay from authorized school account</label><select class="form-select" id="spSourceAccount"><option value="">Loading authorized supplier accounts…</option></select><div class="form-text">The selected source account is recorded on every disbursement and checked against the chosen channel.</div></div></div>
  <div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Approved supplier liabilities</strong><button class="btn btn-primary" id="spSubmit" disabled><i class="bi bi-send me-1"></i>Submit selected</button></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th><input type="checkbox" id="spAll"></th><th>Supplier / liability</th><th class="text-end">Outstanding</th><th>Amount to pay</th><th>Channel</th><th>Verified account</th><th>Status</th></tr></thead><tbody id="spBody"><tr><td colspan="7" class="text-center py-5"><div class="spinner-border spinner-border-sm text-primary"></div></td></tr></tbody></table></div></div>
</div>
<?php asset_script($appBase, 'js/pages/supplier_payments.js'); ?>
