<?php $appBase=rtrim(str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'')),'/');if($appBase==='.')$appBase=''; ?>
<link rel="stylesheet" href="<?=htmlspecialchars($appBase)?>/css/pages/uniform-operations.css?v=<?=asset_version('css/pages/uniform-operations.css')?>">
<main class="uniform-workspace">
 <header class="uniform-hero"><div><small>Uniform store · scanner terminal</small><h1>Point of Sale &amp; Dispatch</h1><p>Scan the identity attached to every unit. The journal connects receipt, buyer, payment, cashier and release.</p></div><button class="uniform-action" id="posRefresh"><i class="bi bi-arrow-clockwise"></i> Refresh</button></header>
 <div id="posMessage"></div>
 <nav class="uniform-tabs"><button class="active" data-pos-tab="counter"><i class="bi bi-upc-scan"></i> Counter Sale</button><button data-pos-tab="dispatch"><i class="bi bi-box-arrow-right"></i> Online Dispatch</button></nav>
 <section id="posCounter" class="uniform-grid">
  <div class="uniform-panel"><h2>Scan items</h2><div class="scan-box"><label class="fw-bold" for="posScan">QR / barcode</label><input class="form-control mt-2" id="posScan" autocomplete="off" placeholder="Scan label or enter KPSU code"><p class="scan-help">USB scanners work like a keyboard. Each code may be added once only.</p></div><div id="posLines" class="scan-lines"></div></div>
  <form class="uniform-panel" id="posForm"><h2>Buyer &amp; payment</h2><div class="uniform-form-grid"><div class="uniform-field wide"><label>Staff buyer (optional)</label><select id="posBuyer"><option value="">Walk-in customer</option></select></div><div class="uniform-field wide"><label>Receiving learner (optional)</label><select id="posStudent"><option value="">Not assigned to a learner</option></select></div><div class="uniform-field"><label>Payment account</label><select id="posPayment" required></select></div><div class="uniform-field"><label>Payment reference</label><input id="posReference"></div><div class="uniform-field wide"><label>Approved offer code</label><input id="posDiscount" autocomplete="off" placeholder="Optional"></div><div class="uniform-field wide"><label>Notes</label><textarea id="posNote" rows="2"></textarea></div></div><div class="sale-total"><div><span>Scanned units</span><strong id="posCount">0</strong></div><div><span>Gross subtotal</span><strong id="posGross">KES 0</strong></div><div class="net"><span>Final amount</span><strong>Calculated securely at completion</strong></div></div><button class="uniform-action green w-100 mt-3" id="posComplete" disabled>Complete Sale</button></form>
 </section>
 <section id="posDispatch" class="uniform-grid" hidden><div class="uniform-panel"><h2>Paid orders</h2><div id="dispatchOrders" class="unit-list"></div></div><div class="uniform-panel"><h2>Pack exact units</h2><div id="dispatchSelected" class="empty-state">Select a paid order.</div><div class="scan-box"><input class="form-control" id="dispatchScan" disabled placeholder="Scan an item for the selected order"></div><button class="uniform-action green w-100 mt-3" id="dispatchComplete" disabled>Confirm Dispatch</button></div></section>
</main>
<?php asset_script($appBase,'js/pages/uniform_point_of_sale.js'); ?>
